# Generated by Django 4.2.30 on 2026-08-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
