# Generated by Django 4.2.30 on 2026-08-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sensor_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
