# Generated by Django 4.2.30 on 2026-08-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sensor_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='is_connected',
            field=models.BooleanField(default=True),
        ),
    ]
